## #######################################################################################
## ESP-12E-Witty-12
## #######################################################################################
#
#
## used PINS on ESP-12E-Witty-12
##
## GPIO 5 IR приёмник
## GPIO 14 IR передатчик
##
##
## ----------------------------------------------------------------


######################################################################
# set Переменные
######################################################################
substitutions:
  hostname: "dalnac"
  friendly_name: "DalnAC"
  board: nodemcuv2
  logger_level: debug
  api_key: !secret api_key_12
  ota_password: !secret ota_password_12
  static_ip: 192.168.5.12
  ## ВНИМАНИЕ!!!!
  receiver_pin: "5"
  transmitter_pin: "14"


######################################################################
# set Общие настройки и сенсоры
######################################################################
packages:
  wifi: !include include/wifi.yaml
  ota: !include include/ota.yaml
  web_server: !include include/web_server.yaml
  time: !include include/time.yaml
  esphome: !include include/esphome.yaml
  api: !include include/api.yaml
  logger: !include include/logger.yaml
  captive_portal: !include include/captive_portal.yaml
  device_base: !include include/device_base.yaml

######################################################################
# Дополняем esphome
######################################################################
esphome:
  includes:
  - include/custom/gree.h
  libraries:
  - IRremoteESP8266


######################################################################
# Глобальные переменные
######################################################################
#globals:



######################################################################
# Дополняем api
######################################################################
#api:



######################################################################
# set esp8266
######################################################################
esp8266:
  board: $board
  framework:
    version: recommended


######################################################################
# set esp32
######################################################################
#esp32:

######################################################################
# set esp32_touch
######################################################################
#esp32_touch:


######################################################################
# set i2c
######################################################################
#i2c:


######################################################################
# set uart
######################################################################
#uart:


######################################################################
# set modbus
######################################################################
#modbus:


######################################################################
# set dallas
######################################################################
#dallas:


######################################################################
# set display
######################################################################
#display:


######################################################################
# set text_sensor
######################################################################
#text_sensor:


######################################################################
# set binary_sensor
######################################################################
#binary_sensor:


######################################################################
# set switch
######################################################################
switch:
- platform: custom
  lambda: |-
    auto dysplay = new GreeLightSwitch();
    App.register_component(dysplay);
    return {dysplay};

  switches:
    name: "dysplay"

######################################################################
# set sensor
######################################################################
sensor:
- platform: homeassistant
  name: "TemperatureXiaomi"
  entity_id: sensor.temperature_158d00044a05d7
  id: sensor_temp



######################################################################
# set status_led
######################################################################
#status_led:


######################################################################
# set output
######################################################################
#output:


######################################################################
# set light
######################################################################
#light:


######################################################################
# set climate
######################################################################
climate:

- platform: custom
  lambda: |-
    auto gree = new GreeAC();
    gree->set_temp_sensor(id(sensor_temp));
    App.register_component(gree);
    return {gree};

  climates:
  - name: "Gree"


######################################################################
# set remote_receiver приёмник
######################################################################
remote_receiver:
  pin:
    number: $receiver_pin
    inverted: true
    mode:
      input: true
      pullup: true
  dump: all
  filter: 50us #50us
  idle: 10ms #10ms
  memory_blocks: 3


######################################################################
# set remote_transmitter передатчик
######################################################################
remote_transmitter:
  pin:
    number: $transmitter_pin
    inverted: false
  carrier_duty_percent: 50%